AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Tech Challenge Fase 4 - Microservice 1: Ingestão de Feedback.

Globals:
  Function:
    Timeout: 15
    MemorySize: 512
    Runtime: java17
    Architectures: [x86_64]
    Environment:
      Variables:
        DYNAMODB_TABLE_NAME: !Ref FeedbackTable
        URGENCY_QUEUE_URL: !Ref UrgencyQueue
        # ADICIONADO: Força o Spring a usar este Bean específico
        SPRING_CLOUD_FUNCTION_DEFINITION: processarFeedback

Resources:
  FeedbackTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: FeedbackTable
      PrimaryKey: { Name: id, Type: String }
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

  UrgencyQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: urgency-feedback-queue
      VisibilityTimeout: 60

  IngestionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker
      AutoPublishAlias: live
      SnapStart:
        ApplyOn: PublishedVersions
      Policies:
        - DynamoDBCrudPolicy: { TableName: !Ref FeedbackTable }
        - SQSSendMessagePolicy: { QueueName: !GetAtt UrgencyQueue.QueueName }
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /avaliacao
            Method: post

Outputs:
  IngestionApi:
    Description: "Endpoint da API"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/avaliacao"