AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Tech Challenge Fase 4 - Feedback System (3 Microservices)

Globals:
  Function:
    Timeout: 20
    MemorySize: 512
    Runtime: java17
    Architectures: [x86_64]
    Environment:
      Variables:
        DYNAMODB_TABLE_NAME: !Ref FeedbackTable
        URGENCY_QUEUE_URL: !Ref UrgencyQueue
        URGENCY_TOPIC_ARN: !Ref UrgencyTopic
        REPORT_TOPIC_ARN: !Ref ReportTopic

Resources:
  # --- 1. Persistência e Mensageria ---
  FeedbackTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: FeedbackTable
      PrimaryKey: { Name: id, Type: String }

  UrgencyQueue: # Fila SQS para comunicação Function 1 -> Function 2
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 60 # Tempo para Lambda processar

  # --- 2. Microsserviço 1: Ingestão (API) ---
  IngestionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker
      Environment:
        Variables:
          SPRING_CLOUD_FUNCTION_DEFINITION: processarFeedback # Nome do Bean
      Policies:
        - DynamoDBCrudPolicy: { TableName: !Ref FeedbackTable }
        - SQSSendMessagePolicy: { QueueName: !GetAtt UrgencyQueue.QueueName }
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /avaliacao
            Method: post